//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhandoComWord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrabalhandoComWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um documento do Word no formato (doc ou docx) e tente novamente.
        /// </summary>
        internal static string MensagemSelecioneArquivoWord {
            get {
                return ResourceManager.GetString("MensagemSelecioneArquivoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um roteiro para ser executado no documento selecionado.
        /// </summary>
        internal static string MensagemSelecioneUmRoteio {
            get {
                return ResourceManager.GetString("MensagemSelecioneUmRoteio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisando o conteúdo do arquivo selecionado.
        /// </summary>
        internal static string StatusAnalisandoArquivoWord {
            get {
                return ResourceManager.GetString("StatusAnalisandoArquivoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise concluída foram encontrados %s campos de formulário.
        /// </summary>
        internal static string StatusAnaliseConcluida {
            get {
                return ResourceManager.GetString("StatusAnaliseConcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise concluída nenhum campo de formulário foi encontrado.
        /// </summary>
        internal static string StatusAnaliseSemCampos {
            get {
                return ResourceManager.GetString("StatusAnaliseSemCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um documento do Word no formato (doc ou docx) para começar.
        /// </summary>
        internal static string StatusSelecioneArquivoWord {
            get {
                return ResourceManager.GetString("StatusSelecioneArquivoWord", resourceCulture);
            }
        }
    }
}
